# Generated by Django 4.2.19 on 2025-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_url', models.URLField(unique=True)),
                ('short_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
