# Generated by Django 4.2.19 on 2025-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
