# Generated by Django 4.2.19 on 2025-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_shortenedurl_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(),
        ),
    ]
